spring:
  application:
    name: socialnetwork
  datasource:
    url: jdbc:postgresql://localhost:5432/socialnetwork_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8083

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
  file:
    name: logs/application.log
    path: logs